# This is a basic workflow to help you get started with Actions

name: CI with java and gradle

# Controls when the workflow will run
on: [push]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:     

      # Runs a single command using the runners shell
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: CheckOut repo code
        uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        
      - name: Build with Gradle
        run: ./gradlew build
